console.log('Hello World');

// I LIke 'Apple' very much!

console.log("i love 'Apple' very much");
console.log('i love \'Apple\' very much');


// i want to learn "Javascript" asap!
console.log("i want to learn \"Javascript\" asap!");


// the path of the file is Techglobal\Desktop\hello.js
console.log('the path of the file is Techglobal\\Desktop\\hello.js')

// if u do 1 \ its \\ of you do \\ its \\\\

// 
console.log('Hello\nWorld');
console.log('Hello\tWorld');
console.log('Hello,\n\n\t \Im writing this letter for... \nWell first of all');


// ESG template Literals (2-15) - Baclticks

console.log(`i want to learn "Javascript"
and 'TypeScript' asap!`);

console.log(`you
can
do
it`);






