let myFavoriteBook = 'amok';

// you can use igits in your variable name anywhere but first character
let myFavoriteBook2 = 'My Name Is Red';

// you cannot use special characters in your variable name except _ and currencies $
let $myCar = 'Mercedes';
let $my_Balance = '100';

// you cannot use reserved keyword as you variable names
// let class = 'Math'; // Error
let _class = 'math';

let phoneNumber = '000-000-0000'; //use meaningful name not just X its conventional : preferred


let name1, name2, name3;

const firstDay = 'sunday', secondDay = 'monday', thirdDay = 'tuesday'
// instead of three lines use one

let num1 = 10, num2, num3 = 25.5, num4;

console.log(num1); // 10
console.log(num2); // undefined
console.log(num3); // 25.5
console.log(num4); // undefined